openai:
    model: gpt-3.5-turbo
    api:
        key: #chatgpt api key disabled: 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 - chatgpt api key disabled
        url: https://api.openai.com/v1/chat/completions
