server:
  port: 8888
spring:
  application:
    name: galdino-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wagnergaldino/curso-config-server
          #username: username
          #password: password
          default-label: master
          search-paths:
          - 'greeting-service*'

